### ISSUE TITLE
[Error] MemoryError when opening textures

### ISSUE THREAD

**Issue by e-murray** [theFroh/imagepacker#7]
When running objuvpacker.py in cmd, it gets as far as opening the textures before running into a MemoryError. Not sure if there are just simply too many textures for it to process (~900 .bmp files), I'm running 64 bit Python on a machine with 64GB of RAM so I can't see the system being the problem. 
![MemoryError](https://user-images.githubusercontent.com/52741387/63250951-aeff5d00-c264-11e9-9ab1-46aa0525994d.png)

**Comment by theFroh** [comment]
Wow, yeah that's interesting. What's the sum total size of your 900 BMPs? And what's your RAM usage look like (check Window's task manager) while running this?

I definitely did not write this with huge texture files in mind (be that due to many medium-sized textures, or a few huge files). I'd probably need to move to a smarter streaming procedure to free memory as quickly as possible (or maybe I'm just doing something silly with the memory as-is and not freeing it as soon as I can!)

When I get the chance I'll review and see what might be occurring.

Depending on your situation, I'd try batch-converting your textures into a format which lends itself to smaller files -- say, PNG if you are concerned about losslessness, or JPG. Not too sure if this will reduce working memory used when they're read -- for all I know PIL might decompress them into memory anyway! But worth a shot anyway.

If you get any issues with it *finding* the texture files after doing a batch-conversion, open your model's MTL file in a text editor and do a find-replace for your old file extension (".bmp") to the new file extension (".jpg").

Cheers!

**Comment by e-murray** [comment]
I double checked and realised I have both 32 & 64 bit Python and was defaulting to the 32 bit version. so changing to the 64bit version solved the problem. 

The .bmp images come to around 370MB total so not huge. I've been using your script to consolidate the texture files from an .obj exported from Google Earth which is the reason for so many textures, it makes subsequent texture painting in Blender a piece of cake. 

Many thanks for your helpful reply.

**Comment by theFroh** [comment]
Neat! And good to hear. There's definitely a few low-hanging fruit in terms of memory savings that I spotted, so I might roll an update out to help out there anyway.

Then again, I've been meaning to take this tool and give it an interactive GUI at some point too, to help with trickier UV wrapping (i.e. models that exploit UV coordinates wrapping around for repeat-detail), 

Anyway, glad to see it is still helping people out.
